// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDershkgo8OoKx6m3hTX9yY4JTvDh-nIdc',
    appId: '1:650749203202:android:5c76cf195914ded2bbe81b',
    messagingSenderId: '650749203202',
    projectId: 'computacion-movil-a1z9',
    storageBucket: 'computacion-movil-a1z9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo9AQh4zhEnxoNMG0fWuDckM3eMwZQg6w',
    appId: '1:650749203202:ios:c5c867c99e0ad470bbe81b',
    messagingSenderId: '650749203202',
    projectId: 'computacion-movil-a1z9',
    storageBucket: 'computacion-movil-a1z9.appspot.com',
    androidClientId: '650749203202-u207d1lbk82pqhjbmclph36965kscnmf.apps.googleusercontent.com',
    iosClientId: '650749203202-2a68oeo4f9fnct56l69b1uidce0piv5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.compuExamen',
  );

}